authors:
  liWanr:
    name: liWanr
    description: 作者
    avatar: /assets/avatar.png
    url: https://liwanr.com
  DAI X.L.:
    name: DAI X.L.
    description: 贡献
    avatar: https://dxlcq.cn/assets/head.png
    url: https://dxlcq.cn