authors:
  liWanr:
    name: liWanr
    description: 作者
    avatar: /assets/avatar.png
    email: itsWanr@iCloud.com
    url: https://liwanr.com
  Wyman:
    name: 黄伟文
    description: 作词
    avatar: https://scontent-fra5-1.cdninstagram.com/v/t51.82787-19/610530541_18557446162020973_7421166547028531539_n.jpg?stp=dst-jpg_s160x160_tt6&_nc_cat=100&ccb=7-5&_nc_sid=bf7eb4&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=QPVB66VfYckQ7kNvwG0Hcqt&_nc_oc=Adrvwg9awiTtGnBOPzgp4LNca43LRQq6nDd_UA5yqub_Mm5zk1DJWlp0qVVkKujaogQ&_nc_zt=24&_nc_ht=scontent-fra5-1.cdninstagram.com&_nc_gid=JR72pJrxrUrCI4OX2ejQCw&_nc_ss=7b6a8&oh=00_AQO7q4RHjjBAA8IeRgxkK1KPE85UBSbOONI_5Hu1UA3y3A&oe=6ACD4BBC
    email: whoiswyman@gmail.com