site_name: liWanr
site_url: https://liWanr.com
repo_name: GitHub/liWanr
repo_url: https://github.com/liWanr/liWanr.github.io
dev_addr: 0.0.0.0:8000

site_description: "极客向个人技术站点，内容涵盖编程、网络以及真实项目实践，关注技术落地与设计体验，记录持续探索与长期创作。" 
copyright: |
  <div style="font-feature-settings: 'ss04' off;">
  &copy; 2023-2026 <strong>liWanr</strong> All Rights Reserved.
  <img src="https://views.whatilearened.today/views/github/liWanr/liWanr.github.io.svg" alt="views" style="width: 56px; position: relative; top: 2.8px;">
  <small>
  |
  <a href="https://icp.gov.moe/?keyword=20261874" style="font-feature-settings: 'ss04' off;" target="_blank">萌ICP备 20261874 号</a>
  </small>
  </div>

theme:
  name: material
  language: zh
  favicon: assets/favicon.png
  custom_dir: overrides
  icon:
    logo: local/logo
    repo: lucide/github
  font: 
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: 跟随系统

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: liwanr
      accent: liwanr
      toggle:
        icon: lucide/sun
        name: 浅色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: liwanr
      accent: liwanr
      toggle:
        icon: lucide/moon
        name: 深色模式
    
  features:
    - announce.dismiss
    - content.action.view         # 在页面顶部添加查看链接，指向 GitHub 上的对应文件，方便读者查看源内容
    - content.code.annotate       # 在代码关键位置添加图标 + 鼠标悬停提示
    - content.code.copy           # 在代码块中添加一键复制按钮，无需先选中内容
    - content.footnote.tooltips   # 将脚注渲染为行内工具提示（tooltip），无需跳转即可阅读
    - content.tabs.link           # 同步切换内容标签页标题相同的标签
    - content.tooltips            # 美化 title 提示渲染
    - navigation.indexes          # 章节索引页功能，允许文档直接挂载到章节下（适合概览页）
    - navigation.path             # 显示路径面包屑导航（在页面标题上方）
    - navigation.tabs             # 在大屏幕下，将顶级章节渲染为头部下方的菜单标签页
    - navigation.tabs.sticky      # 粘性标签页：向下滚动时标签页固定在头部下方始终可见
    - navigation.top              # 当用户向下滚动后开始向上滚动时，显示“返回顶部”按钮
    - navigation.tracking         # 锚点跟踪：地址栏 URL 会自动更新为当前高亮的目录锚点
    - search.highlight            # 搜索跳转后高亮匹配内容
    - toc.follow                  # 目录锚点跟随：侧边栏会自动滚动，让当前激活的锚点始终可见

markdown_extensions:
  - abbr                          # 缩写支持
  - attr_list                     # 属性列表（用于按钮、class 等）
  - def_list                      # 定义列表语法
  - footnotes                     # 脚注支持
  - md_in_html                    # 允许在 HTML 中写 Markdown
  - tables                        # Markdown 表格支持

  - toc:                          # 目录锚点
      permalink: ⚓︎
      permalink_title: 锚点
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

  - pymdownx.blocks.admonition    # 新，警示块
  - pymdownx.blocks.caption       # 新，图片标题与对齐支持
  - pymdownx.blocks.definition    # 新，定义块
  - pymdownx.blocks.details       # 新，折叠警示块
  - pymdownx.blocks.html          # 新，自定义 HTML 块支持
  - pymdownx.caret                # 上标/下标语法
  - pymdownx.inlinehilite         # 行内代码高亮
  - pymdownx.magiclink            # 魔法链接
  - pymdownx.mark                 # 文本高亮标记
  - pymdownx.progressbar          # 进度条语法
  - pymdownx.smartsymbols         # 将某些字符序列转换为相应的符号，例如版权符号或分数
  - pymdownx.tilde                # 删除线与下标语法

  - pymdownx.blocks.tab:          # 新，内容标签页
      alternate_style: True
      combine_header_slug: True
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons: ["overrides/.icons"]

  - pymdownx.highlight:
      guess_lang: true
      linenums: true                    # 为所有代码块添加行号
      linenums_style: "pymdownx-inline" # 行号样式
      auto_title: false                 # 自动为所有代码块添加标题 ，显示所用语言的名称
      line_spans: "__span"              # 用于行级高亮的 span 标识
      anchor_linenums: true             # 允许代码行号作为锚点
      pygments_lang_class: true
  
  - pymdownx.keys:
      key_map: {"a":"a", "b":"b", "c":"c", "d":"d", "e":"e", "f":"f", "g":"g", "h":"h", "i":"i", "j":"j", "k":"k", "l":"l", "m":"m", "n":"n", "o":"o", "p":"p", "q":"q", "r":"r", "s":"s", "t":"t", "u":"u", "v":"v", "w":"w", "x":"x", "y":"y", "z":"z", "A":"A", "B":"B", "C":"C", "D":"D", "E":"E", "F":"F", "G":"G", "H":"H", "I":"I", "J":"J", "K":"K", "L":"L", "M":"M", "N":"N", "O":"O", "P":"P", "Q":"Q", "R":"R", "S":"S", "T":"T", "U":"U", "V":"V", "W":"W", "X":"X", "Y":"Y", "Z":"Z", "asterisk":"*", "at":"@","and":"&","sharp":"#", "percent":"%", "caret":"^", "dollar":"$"}

  - pymdownx.quotes:              # 更现代的引用
      callouts: true

  - pymdownx.snippets:            # 自动引入缩写定义文件
      auto_append: ["includes/abbreviations.md"]             

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tasklist:            # 使用自定义复选框样式
      custom_checkbox: true


extra:
  generator: false                # 移除 “Made with Zensical” 声明
  annotate:
    Bash: [".s2"]
  analytics:
    provider: google
    tracking_id: G-JJZ9XN4L96

  status:
    new: 最新发布

  tags:                          # 使用标签对任何页面进行分类，标签将作为页面元数据的一部分
    Net: NetWork
    Tech: Technology
    Factoid: Factoid
    Git: Git
  
  social:
    - icon: material/folder
      link: /public/
      name: Public
    
    - icon: material/folder-lock
      link: /private/
      name: Private
    
    - icon: simple/openwrt
      link: http://10.0.0.1
      name: Openwrt
    
    - icon: lucide/hard-drive-upload
      link: http://10.0.0.1:16601
      name: Lucky

    - icon: material/google-translate
      link: https://translate.google.com/?hl=zh-CN&sl=zh-C
      name: Translate

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/search.css

extra_javascript:
  - path: assets/javascripts/extra.js
    async: true

nav:
  - Home: index.md
  - DevOps:
      - dev/zip-unzip.md
      - dev/git.md
      - dev/vim.md
      - Docker:
          - dev/docker/index.md
          - dev/docker/install.md
          - dev/docker/use.md
          - dev/docker/app-deploy.md
          - dev/docker/custom-img.md
      - VPN:
          - dev/vpn/index.md
          - dev/vpn/bleachwrt.md
          - dev/vpn/wire-guard.md
          - dev/vpn/openvpn-client.md
      - Nginx:
          - dev/nginx/index.md
          - dev/nginx/reverse-proxy.md
      - dev/mysql.md
      - dev/ubuntu-enable-net.md
      - dev/samba.md
  - Blog:
    - blog/posts/zensical-pro-tips.md
    - blog/posts/hackrf-firmware-maint.md
    - blog/posts/github-badge.md
    - blog/posts/chrome-search-new-tab.md
    - blog/posts/dns-explain.md
    - blog/posts/jetbrains-active-free.md
    - blog/posts/dual-boot-time-sync.md
    - blog/posts/usb-secure-boot.md
    - blog/posts/remove-win-v-shortcut.md
    - blog/posts/nvidia-control-panel-fs-corrupt.md
    - blog/posts/execution-breakdown.md
    - blog/posts/activate-typora.md
    - blog/posts/apple-music.md
    - blog/posts/apple-ai.md
  - Recom:
    - recom/website.md
    - recom/open-source.md
    - recom/tools.md
    - recom/good-blogs.md