authors:
  liWanr:
    name: liWanr
    description: 作者
    avatar: /assets/avatar.png
    email: itsWanr@iCloud.com
    url: https://liwanr.com
  Jiao:
    name: DAI X.L.
    description: 贡献
    avatar: https://dxlcq.cn/assets/head.png
    email: dxlcq@outlook.com
    url: https://dxlcq.cn
  Wyman:
    name: 黄伟文
    description: 作词
    avatar: https://scontent-lax3-2.xx.fbcdn.net/v/t1.6435-9/177806276_314996203331016_1979412036351588459_n.jpg?stp=dst-jpg_tt6&cstp=mx750x750&ctp=s750x750&_nc_cat=100&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=wuprVZAhTAwQ7kNvwGtrOyz&_nc_oc=AdrxjJxNO-frz1J723XA9uboan0FUwKDEI-WMu8TwmseORZAkvGBhGqpchDSv8k2w-4&_nc_zt=23&_nc_ht=scontent-lax3-2.xx&_nc_gid=3eLnFaQYxZ_6xDCRm1uR1A&_nc_ss=7b289&oh=00_AQAl_FWqF6AAwGIhXDFFVr7BfXp9QVxMMiTL2HlKgMXqww&oe=6A7C0F2E
    email: whoiswyman@gmail.com