authors:
  liWanr:
    name: liWanr
    description: 作者
    avatar: /assets/avatar.png
    email: itsWanr@iCloud.com
    url: https://liwanr.com
  Jiao:
    name: DAI X.L.
    description: 贡献
    avatar: https://dxlcq.cn/assets/head.png
    email: dxlcq@outlook.com
    url: https://dxlcq.cn
  opensource:
    name: 开源倡议
    description: 开源倡议
    avatar: https://i0.wp.com/opensource.org/wp-content/uploads/2023/01/cropped-cropped-OSI_Horizontal_Logo_0-e1674081292667.png
    url: https://opensource.org/
  TMDB:
    name: TMDB
    description: 资源
    avatar: https://www.themoviedb.org/assets/2/favicon-16x16-b362d267873ce9c5a39f686a11fe67fec2a72ed25fa8396c11b71aa43c938b11.png
    url: https://www.themoviedb.org/